Connect/stackprj/stackbase/urls.py
from django.urls import path ,include
from stackbase import views
# from poll import views as poll_views

app_name="stackbase"

urlpatterns = [
    path("",views.home,name="home"),
    path("home/",views.home,name="home"),
    path("base/",views.base,name="about"),
    path("questions/",views.QuestionListView.as_view(), name="question-list"),
# ye mujhe upar wala view as view krke isliye bhejna pada kyunki ye class hai?
    path("questions/<int:pk>/",views.QuestionDetailView.as_view(),name="question-detail"),
    path("questions/new",views.QuestionCreateView.as_view(),name="question-create"),
    path("questions/<int:pk>/update",views.QuestionUpdateView.as_view(),name="question-update"),  # ye path create view wali hi automatically template use krlega ye inbuilt views hain django ke aise hi kaam krte hain , defualt mein
    path("questions/<int:pk>/delete",views.QuestionDeleteView.as_view(),name="question-delete"), 
    path("questions/<int:pk>/comment",views.AddComment.as_view(),name="question-comment"), 



    # additonal pools and goodies
    # path("polls/",views.polls,name="polls"),

    path("goodies/",views.goodies,name="goodies"),
    path("like/<int:pk>", views.like_view, name="like_post"),

    
    # poll section
    # # path('', poll_views.home, name='home'),
    path('poll/list/', views.list, name='poll_list'),
    # path('poll/create/', views.create, name='poll_create'),
    path('vote/<poll_id>/', views.vote, name='poll_vote'),
    path('results/<poll_id>/',views.results, name='poll_results'),
 
    
]


# question_confirm_delete.html apne aap ye iss html page pe search krne lg gya toh isse hi file bana de rha jab yhi search kr rha hai bo toh

Connect/stackprj/stackprj/urls.py
from django.contrib import admin
from django.urls import path , include
from stackusers import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("stackbase.urls")),


    #Authentications

    path("register/", user_view.register,name="register" ),
    # path("login/", auth_views.LoginViews.as_login(),name="login")
    path("login/", auth_views.LoginView.as_view(template_name="stackusers/login.html"),name="login"),
    # path("logout/", auth_views.LogoutView.as_view(template_name="stackusers/logout.html"),name="logout"),
    path("logout/", user_view.logout_view, name="logout"),

    # profile system
    path("profile/",user_view.profile,name="profile"),
    path("profile/update",user_view.profile_update,name="profile_update"),
    
    
    


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Connect/stackprj/stackbase/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
# from ckeditor.fields import RichTextField
# from tinymce.models import HTMLField
# from ckeditor_uploader.fields import RichTextField
# Create your models here.


class Question(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    title= models.CharField(max_length=10000)
    content=models.TextField(null =True, blank=True)
    # content = RichTextField()
    likes=models.ManyToManyField(User, related_name="question_post")
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username} - Question"
    
    def get_absolute_url(self):
        return reverse("stackbase:question-detail", kwargs={"pk": self.pk})
    # upar wali line itna kh ri hai ki bas jab question post krne ke baad question-detail wale url mein jo primary
# se create hua hai question wahi kholke de dena 
    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    question=models.ForeignKey(Question,related_name="comment", on_delete=models.CASCADE) 
# upar wali line question model ko pura inherit kr ri tabhi mein neeche question model ki cheezein use kr paa rha?
    name=models.CharField(max_length=100)
    content=models.TextField(null=True,blank=True)
    # content= RichTextField()
    date_created=models.DateTimeField(default=timezone.now)

    def __str__(self): # ye database mein heading kaise show hogi bo
        return "%s - %s" %(self.question.title , self.question.user)
    
    def get_absolute_url(self):
        return reverse("stackbase:question-detail", kwargs={"pk": self.pk})
    
    def save(self , *args,**kwargs):
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['-date_created'] 
        # yha ise humne order mein laa diya time ke hisaab se.
        # ye save function exactly save kr rha comment ? agr haa toh .... pata krna hai thoda iske baare mein.




# polls

class Poll(models.Model):
    question = models.TextField()
    option_one = models.CharField(max_length=30)
    option_two = models.CharField(max_length=30)
    option_three = models.CharField(max_length=30)
    option_one_count = models.IntegerField(default=0)
    option_two_count = models.IntegerField(default=0)
    option_three_count = models.IntegerField(default=0)
    date_created = models.DateTimeField(default=timezone.now)

    def total(self):
        return self.option_one_count + self.option_two_count + self.option_three_count
    def __str__(self):
        return f"{self.question}"
    class Meta:
        ordering = ['-date_created'] 

Connect/stackprj/stackbase/forms.py
from .models import Comment ,Poll
from django import forms
from django.forms import ModelForm

class CommentForm(forms.ModelForm):
    #mujhe thoda idea toh lg rha hai naam dekh ke ki ye arguent kaam kaise karta hai but actually iska content documentation mein check krunga , if i did further work in web development
    
    class Meta:
        model=Comment
        fields=["name","content"]


# yha hum html ni django ke inbulit cheez form ka use kr re widgets dictionary mein
        widegts={
            "name": forms.TextInput(attrs={"class":"form-control"}),
            "body": forms.Textarea(attrs={"class":"form-control"}),
        }



class CreatePollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ['question', 'option_one', 'option_two', 'option_three']

Connect/stackprj/stackbase/views.py
from django.forms import forms 
from .forms import CreatePollForm
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponseRedirect , HttpResponse
from django.urls import reverse_lazy 
from django.views.generic import ListView,DetailView,CreateView , UpdateView , DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin , LoginRequiredMixin
from .models import Question , Comment , Poll
from .forms import CommentForm
from django.shortcuts import render, redirect

# Create your views here.
opera = Question.id
def home(request):
    return render(request, "home.html")

def base(request):
    return render(request, "base.html")

# views mein pehli baar class banaya hai

# CRUD function
class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    # upar wali line kah ri hai jo bhi iss class mein hai bo iss questions variable mein daal do
    ordering = ['-date_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ""
        if search_input:
            context['questions'] = context['questions'].filter(title__icontains = search_input)
            context['search_input'] = search_input
        return context
def like_view(request, pk):
    post = get_object_or_404(Question, id=request.POST.get('question_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse_lazy('stackbase:question-detail', args=[str(pk)]))

class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        something = get_object_or_404(Question, id=self.kwargs['pk'])
        total_likes = something.total_likes()
        liked = False
        if something.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['total_likes'] = total_likes
        context['liked'] = liked
        return context

class QuestionCreateView(LoginRequiredMixin,CreateView):
    model=Question
    fields =  ["title","content"]
    def form_valid(self,form):
        form.instance.user=self.request.user # jo user login hai wahi bhej paayega question
        return super().form_valid(form) # ye line databse mein add kraegi sayd hamara question.

class QuestionUpdateView(UserPassesTestMixin,LoginRequiredMixin,UpdateView):
    model=Question
    fields =  ["title","content"]
    
    # def form_valid(self,form):
    #     form.instance.user=self.request.user # jo user login hai wahi bhej paayega question
    #     return super().form_valid(form)
    
    # ye wala form_valid function create ke liye likha toh ha aur ye interconnectrd hai aur ek hi template use kr rha toh 2 baar likh ke fayda ni kaam thik se kr rha hai aise toh . toh mein comment kr de rha hu ok.
    # UserPassesTestMixin ye use krne ke le liye aapko test_func() banana pdega
    def test_func(self):
        questions=self.get_object() #.get_object() function hai berrroooo ise call kra kro , mein call ni kr rha rha itni der se bas naam likh ke chor rkha tha aur error khaa rha tha waooo.
        
        if self.request.user == questions.user:
            
            return True 
        return False


class QuestionDeleteView(UserPassesTestMixin , LoginRequiredMixin,DeleteView):
    model= Question
    # success_url = "stackbase:home"  #yha pr hi le rha bo success url button ko href de rha toh kaam ni kr rha 
    success_url=reverse_lazy("stackbase:question-list")
    def test_func(self):
        questions=self.get_object()
        
        if self.request.user == questions.user:
            
            return True 
        else:
            return False
        

'''
error ka solution
error : 

DisallowedRedirect at /questions/3/delete
Unsafe redirect to URL with protocol 'stackbase'

solution:

The error you're encountering is due to the incorrect format of the success_url attribute in your QuestionDeleteView. Instead of providing the URL name directly, you should use the reverse_lazy function to dynamically resolve the URL name to its actual URL.

Here's the corrected version of your QuestionDeleteView:

'''



class CommentDetailView(LoginRequiredMixin,CreateView):
    model=Comment
    form_class= CommentForm #ye form_class hamari forms,py se template uthayegi aur jis jgh assign kroge waha waha bo kaam kregi vaise jaise btaoge abhi toh create view ki jha redirecting hogi wahi se template uthayega ok.
    success_url="stackabse/question_detail.html"
    
    # ab yha form valid method to get valid response from the form and save it in databse
    # ye form wala argument khi define ni hai but ja kaise rha?
    def form_valid(self,form):
        form.instance.question_id=self.kwargs["pk"]
        return super().form_valid(form)
        
    success_url= reverse_lazy("stackabse:question-detail")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = Comment.objects.filter(question_id=self.kwargs["pk"]).order_by('date_created')
        context['comments'] = comments
        return context


class AddComment(LoginRequiredMixin,CreateView):
    model=Comment
    form_class=CommentForm
    template_name="stackbase/question_answer.html"

    def form_valid(self,form):
        form.instance.question_id=self.kwargs["pk"]
        return super().form_valid(form)
    # success_url= reverse_lazy("stackbase:question-detail", kwargs={'pk': self.request.opera}) #if i can pass the id of the question.id model with this 
    # success_url= reverse_lazy("stackbase:question-detail")
    def get_success_url(self):
        return reverse_lazy("stackbase:question-detail", kwargs={'pk': self.kwargs["pk"]}) #but ye thik kaam kr rha
        # return reverse_lazy("stackbase:question-detail", kwargs={'pk': self.opera}) opera wala trika mein dekhunga ji abhi ismein problem hai ye kaam ni kr rha thik se .



        # 

# def polls(request):
#     return render(request,"polls.html")
def goodies(request):
    return render(request,"goodies.html")



# polls





def list(request):
    polls = Poll.objects.all()
    ordering = ['-date_created']
    context = {
        'polls' : polls
    }
    return render(request, 'stackbase/list.html', context)

# def create(request):
#     if request.method == 'POST':
#         form = CreatePollForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('home')
#     else:
#         form = CreatePollForm()
#     context = {
#         'form' : form
#     }
#     return render(request, 'create.html', context)

def vote(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)

    if request.method == 'POST':

        selected_option = request.POST['poll']
        if selected_option == 'option1':
            poll.option_one_count += 1
        elif selected_option == 'option2':
            poll.option_two_count += 1
        elif selected_option == 'option3':
            poll.option_three_count += 1
        else:
            return HttpResponse(400, 'Invalid form')

        poll.save()

        return redirect('stackbase:poll_results', poll.id)

    context = {
        'poll' : poll
    }
    return render(request, 'stackbase/vote.html', context)

def results(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    context = {
        'poll' : poll
    }
    return render(request, 'stackbase/results.html', context)

Connect/stackprj/stackbase/templates/stackbase/list.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        #fh3{
            text-align: left;
            font-size: 19px;
            padding-top: 15px;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 15px;
                text-align: left;
            }
        }
        #fh6{
            text-align: right;
            font-size: 15px;
            /* padding-bottom: 20px; */
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: right;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        a{
            color: rgb(0, 132, 255);
        }
        a:hover{
            text-decoration: none;
            color: darkblue;
            
        }
        h5{
            color: rgb(133, 133, 133);
        }
    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <h1 id="fh1">Poll Questions</h1>
            {% comment %} {% if user.is_authenticated %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url "stackbase:question-create" %}" style="color: white; text-decoration: none;">Top Polls</a></button>

            {% endif %} {% endcomment %}
        </div>
        <div class="list-question">
            <div class="questions">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Available Polls</h3>
                            </div>
                                
                            <ul class="list-group">
                                {% for poll in polls %}
                                <li class="list-group-item">
                                    <strong>{{ poll.question }}</strong>
                                    <span class="pull-right">
                                        <a href="{% url 'stackbase:poll_vote' poll.id %}" class="btn btn-info btn-xs">Vote</a> &nbsp;
                                        <a href="{% url 'stackbase:poll_results' poll.id %}" class="btn btn-default btn-xs">View Results</a> &nbsp;
                                    </span>
                                </li>
                                {% endfor %}
                            </ul>
                
                        </div>
                    </div>
                </div>
            </div>
        </div>   
    </div>
</body>
</html>
{% endblock content %}

Connect/stackprj/stackbase/templates/stackbase/question_detail.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        /* .list-question{
            height: 400px;
            background-color: rgb(255, 219, 173);
        } */
        #fh3{
            text-align: center;
            font-size: 30px;
            padding-top: 20px;
            text-align: left;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 17px;
                text-align: left;
            }
        }
        #fh6{
            text-align: left;
            font-size: 15px;
            /* padding-top: 20px; */
            padding-bottom: 20px;
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: left;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        
    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <!-- <h1 id="fh1">Hey Guys, Let's help :)</h1> -->
            <!-- <button class="btn" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button> -->

            <!-- <div style="margin-top: 55px;">
                <button class="btn btn-primary" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button>
            </div> -->
        </div>
        <div class="list-question">
            <div class="questions">
                <div class="container" style="background-color: rgba(255, 235, 209, 0.808); padding: 5px; box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 5px 0px; border-radius: 20px;" >
                    <h3 id="fh3">{{question.title}}</h3>
                    <hr>
                    <h6 id="fh6">{{ question.content|safe }}</h6>
                    <hr>
                    <h6 id="fh6" style="font-size: 10px; font-style: italic; color: rgb(155, 155, 155); text-align: right;">Asked By: <a href="{% url 'profile' %}">{{ object.user|title }}</a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{ object.date_created|date:"j F, Y" }}</h6>
                    <br>
                        <form action="{% url "stackbase:like_post" object.pk %}" method="POST">
                            {% csrf_token %}
                            {% if user.is_authenticated %}
                                {% if liked %}
                                    <div style="display: flex; align-items: center; margin-left: 10px;">
                                        <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                    </div>
                                {% else %}
                                    <div style="display: flex; align-items: center; margin-left: 10px;">
                                        <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                    </div>
                                {% endif %}
                            {% else %}
                                <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'login' %}">Login</a> to Like Question |  {{ total_likes }} Likes</h5>
                            {% endif %}

                        </form>
                    <br>
                    <h2>Answers...</h2> <br><br><br>

                    {% if not question.comment.all %}
                        <h3>No Answers yet... <a href="">Answer Question</a> </h3>
                    {% else %}
                    {% comment %} yha question.comment.all krne par bo pura comment model ki cheezein inherit kr ri aur question mein humne Question model ko bhi inherit kr rkha tha toh sayd bo bhi use kr skte hum. 
                    
                    ye question.all krne pr toh kuch aur hi ho jayega kyunki Question model ka instance object humne question bana rkha tha. 
                    {% endcomment %}
                        {% for comment in question.comment.all %}
                            <h3 style="font-weight: normal; font-size: 15px;">{{comment.content|safe}}</h3>
                            <h3 style="font-size: 10px;">Answered by: <i><a href="">{{comment.name}}</a> - On: {{comment.date_created|date:"j F, Y"}}</i></h3>
                            <hr>  
                        {% endfor %}
                    {% endif %}



                    <!-- {% if not questions.comments.all %}
                        <h3>No Answers yet... <a href="">Answer Question</a> </h3>
                    {% else %}

                        {% for comment in questions.comments.all %}
                            <h3 style="font-weight: normal; font-size: 15px;">{{comment.body|safe}}</h3>
                            <h3 style="font-size: 10px;">Answered by: <i><a href="">{{comment.name}}</a> - {{comment.date_added|date:"j F, Y"}}</i></h3>
                            <hr>    
                        {% endfor %}
                    {% endif %}

                    <br><br><br><br><br><br>  </form> -->

                    {% comment %} <form action="" method="POST">
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                        {% if liked %}
                            <div style="display: flex; align-items: center; margin-left: 10px;">
                                <button type="submit" name="questions_id" value="{{ questions.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                            </div>
                        {% else %}
                            <div style="display: flex; align-items: center; margin-left: 10px;">
                                <button type="submit" name="questions_id" value="{{ questions.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                            </div>
                        {% endif %}
                        {% else %}
                            <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'login' %}">Login</a> to Like Question |  {{ total_likes }} Likes</h5>
                        {% endif %} {% endcomment %}
                    
                    
                    <a class="btn btn-outline-primary" id="fa" href="{% url "stackbase:question-comment" question.id %}" style="text-decoration: none;">Answer Question</a>
                     <a style="text-decoration: none; " class="btn btn-outline-success" href="{% url "stackbase:question-update" question.id %}">&#x270E;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-danger" href="{% url "stackbase:question-delete" question.id %}">&#x2716;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-secondary" href="{% url "stackbase:question-list" %}">&#x21a9;</a>  
                </div> <br><br>
                    <!-- Answer Section -->
                
                </div> <br>
            </div>
        </div>
        <br>
        
    </div>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script> -->
</body>
</html>
{% endblock content %}