Connect/stackprj/stackbase/urls.py
from django.urls import path ,include
from stackbase import views
# from poll import views as poll_views

app_name="stackbase"

urlpatterns = [
    path("",views.home,name="home"),
    path("home/",views.home,name="home"),
    path("base/",views.base,name="about"),
    path("questions/",views.QuestionListView.as_view(), name="question-list"),
# ye mujhe upar wala view as view krke isliye bhejna pada kyunki ye class hai?
    path("questions/<int:pk>/",views.QuestionDetailView.as_view(),name="question-detail"),
    path("questions/new",views.QuestionCreateView.as_view(),name="question-create"),
    path("questions/<int:pk>/update",views.QuestionUpdateView.as_view(),name="question-update"),  # ye path create view wali hi automatically template use krlega ye inbuilt views hain django ke aise hi kaam krte hain , defualt mein
    path("questions/<int:pk>/delete",views.QuestionDeleteView.as_view(),name="question-delete"), 
    path("questions/<int:pk>/comment",views.AddComment.as_view(),name="question-comment"), 



    # additonal pools and goodies
    # path("polls/",views.polls,name="polls"),

    path("goodies/",views.goodies,name="goodies"),
    path("like/<int:pk>", views.like_view, name="like_post"),

    
    # poll section
    # # path('', poll_views.home, name='home'),
    path('poll/list/', views.list, name='poll_list'),
    # path('poll/create/', views.create, name='poll_create'),
    path('vote/<poll_id>/', views.vote, name='poll_vote'),
    path('results/<poll_id>/',views.results, name='poll_results'),
 
    
]


# question_confirm_delete.html apne aap ye iss html page pe search krne lg gya toh isse hi file bana de rha jab yhi search kr rha hai bo toh

Connect/stackprj/stackprj/urls.py
from django.contrib import admin
from django.urls import path , include
from stackusers import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("stackbase.urls")),


    #Authentications

    path("register/", user_view.register,name="register" ),
    # path("login/", auth_views.LoginViews.as_login(),name="login")
    path("login/", auth_views.LoginView.as_view(template_name="stackusers/login.html"),name="login"),
    # path("logout/", auth_views.LogoutView.as_view(template_name="stackusers/logout.html"),name="logout"),
    path("logout/", user_view.logout_view, name="logout"),

    # profile system
    path("profile/",user_view.profile,name="profile"),
    path("profile/update",user_view.profile_update,name="profile_update"),
    
    
    


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Connect/stackprj/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Campus Connect - Feedback web app, &amp; Building Responsive platform</title>
    <link rel="shortcut icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196">
    <link rel="apple-touch-icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a">
    <link rel="image_src" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <!-- <link rel="stylesheet" href="assets/css/main.css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        /* Custom CSS for background photo */
        .bg-photo {
            background-image: url('https://c1.wallpaperflare.com/preview/400/918/406/paper-background-writing-school.jpg');
            background-size:cover;
            background-position: top center;
            min-height: 80vh; /* Set the minimum height to full viewport height */
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: white; /* Set text color to contrast with the background */
            background-repeat: no-repeat;
        }
        .foot {
            position:static;
            left: 0;
            bottom: -50px; /* Start off-screen */
            width: 100%;
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px 0;
            transition: bottom 0.3s; /* Add smooth transition effect */
}

        .foot.slided {
            bottom: 0; /* Slide to visible position */
}
    </style>

</head>
<body>

<header>

<div class="nav-container">
    <nav>
        <div class="nav-brand">
            <div class="hamburger-menu-container">

                <div class="hamburger-menu">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
                <div class="nav-dropdown-menu">
                    <a href="#" class="current-link">Home</a>
                    <h5>Public</h5>
                    <ul class="nav-ul">
                        <li class="nav-item">
                            <i class="fas fa-globe-europe"></i>
                            <a href="" class="nav-link">Stack Overflow</a>
                        </li>
                        <li class="nav-item"><a href="#" class="nav-link">Tags</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Users</a></li>
                    </ul>
                    <h5>Find a Job</h5>
                    <ul class="nav-ul">
                        <li class="nav-item"><a href="#" class="nav-link">Jobs</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Companies</a></li>
                    </ul>
                    <h5>Teams <a href="#" >What's this ?</a></h5>
                    <a href="#" class="nav-link">
                        <i class="fas fa-briefcase"></i>
                        <span>Free 30 Day Trial</span>
                    </a>
                </div>
            </div>

            <a href="{% url "stackbase:home" %}" class="nav-icon">
                <i class="fab fa-stack-overflow"></i>
                <a href="{% url "stackbase:home" %}" style="text-decoration: none; color: black;"><div class="nav-icon-text">Campus <span class="nav-bold-text">Connect</span></a>
                {% comment %} <div class="nav-icon-text">stack <span class="nav-bold-text">overflow</span> {% endcomment %}

                
                </div>
            </a>
        </div>
        <div class="nav-base-links">
            <ul>
                <li><a href="{% url "stackbase:home" %}">Leaderboard</a></li>
                <li><a href="{% url "stackbase:question-list" %}">Discussion</a></li>
                <li><a href="{% url "stackbase:poll_list" %}">Polls</a></li>
                <li><a href="{% url "stackbase:goodies" %}">Goodies</a></li>
            </ul>
        </div>
        <div class="nav-search">
            <div class="search-container">
                <i class="fas fa-search"></i>
                <form action="" method="GET">
                    <input type="text" id="" name="search-area" placeholder="Search...">
                    <button type="submit" style="margin-left: 340px; border-radius: 25px; border: none; padding: 8px;">Search</button>
                </form>
            </div>
            <div class="search-hints">
                <div class="search-arrow-up"></div>
                <div class="search-hint-body">
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>[tag] </span> search within a tag</div>
                        <div class="hint-text"><span>user:1234 </span>  search by author</div>
                        <div class="hint-text"><span>"words here"</span> exact phrase </div>
                    </div>
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>answers:0</span> unanswered questions</div>
                        <div class="hint-text"><span> score:3  </span> posts with a 3+ score</div>
                    </div>
                </div>
                <div class="search-hint-footer">
                    <a href="#" class="btn">Ask a question</a>
                    <a href="#" class="search-help">Search help</a>
                </div>
            </div>

        </div>
        <div class="nav-right-buttons">
            <div class="search-btn">
                <i class="fas fa-search"></i>
            </div>
{% comment %} 
            <a href="{% url "login" %}" class="btn btn-login">Log in</a>
                <a href="{% url "register" %}" class="btn btn-register">Sign up</a>  {% endcomment %}
            {% if user.is_authenticated %}
                <a href="/profile" class="btn btn-login">Profile</a>
                <a href="{% url 'logout' %}" class="btn btn-register">Logout</a> 
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-login">Log in</a>
                <a href="{% url 'register' %}" class="btn btn-register">Sign up</a> 
            {% endif %}  
        </div>
    </nav>
</div>
<!-- <h1 style="font-size: 20px;">hello</h1> -->

<!-- to show messages the under given code works for. they are django messages -->
    <div style="margin-top: 10px;">
        {% if messages %}
        {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        <h4 style="text-align: center;">{{ message }}</h4>
      </div>
      {% endfor %}
    {% endif %}
    </div>

        
</header>

<!-- Add block content here -->
<!-- Add enbdblock content here -->

{% block content %}



{% endblock content %}

<!-- <section class="jobs">
    <div class="container">

        <div class="jobs-content">
            <h3 class="jobs-title">Looking for a job?</h3>
            <div class="jobs-body">
                    <div class="jobs-items">
                        <div class="column">
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-tech.svg?v=42f011c01763" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse jobs by technology</p>
                            </div>
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-salary.svg?v=401840ff8931" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse jobs by salary</p>
                            </div>
                        </div>
                        <div class="column">
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-visa.svg?v=1f3acc6dc772" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse jobs by visa sponsorship</p>
                            </div>
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-remote.svg?v=a4b4d1b5a80c" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse remote-friendly jobs</p>
                            </div>
                        </div>
                    </div>
                    <div class="jobs-btn">
                        <div class="btn btn-orange jobs-btn">View all jobs</div>
                    </div>
            </div>
        </div>
    </div>
</section> -->

<!-- <footer class="footer">
    <img src="https://cdn.sstatic.net/Img/home/robot.svg?v=dfa16a330cbd" alt="" class="footer-robot-img">
<div class="container">
    <div class="footer-content">
        <div class="footer-icon">
            <i class="fab fa-stack-overflow"></i>
        </div>
        
            
            <div class="copyright">
                <p>site design / logo © 2020 Stack Exchange Inc; user contributions licensed under <a href="https://stackoverflow.com/help/licensing">cc by-sa</a>. rev 2020.10.2.37725</p>
            </div>
        </div>
    </div>

</div>
</footer> -->

<!-- <script src="assets/js/main.js"></script> -->
<script src="{% static 'main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
<script>
    function toggleFooter() {
        var footer = document.getElementById('footer');
        footer.classList.toggle('slided');
    }
</script>
</body>
</html>

Connect/stackprj/templates/goodies.html
<strong>Goodies ban jayegi tab add kr denge</strong>

Connect/stackprj/templates/home.html
{% extends 'base.html' %}
{% block content %}
<section class="bg-photo">
    <div class="hero-content">
        <h1 class="hero-title">We <span> <3 </span> people who give Feedbacks</h1>
        <p class="hero-paragraph">
            Those who provide feedback are like architects of improvement, shaping a better tomorrow with their words today
        </p>
        <div class="hero-options ">
            {% if not user.is_authenticated %}
                <a href="{% url "register" %}" class="btn btn-developers">SignUp</a>
                <a href="{% url "login" %}" class="btn btn-businesses">SignIn</a>
            {% else %}
                <a href="{% url "profile" %}" class="btn btn-secondary mx-2">Edit Your Profile</a>
                <a href="{% url "stackbase:question-list" %}" class="btn btn-primary">Latest Discussions</a>
            {% endif %}
            {% comment %} <a href="{% url 'stackbase:question-lists' %}" class="btn btn-developers" style="margin-left: 5px;">Latest Questions</a> {% endcomment %}

        </div>
    </div>
</section>


<section class="for-developers">
   <div class="container">
    
       <div class="section-head">
           <h2 class="section-title">To Feedbackers , By Campus Connect Team
           </h2>
           <div class="section-line"></div>
           <p class="section-description">People who participate in feedbacks often have a strong desire to improve themselves, their environment, or the systems they are a part of. They see feedback as a valuable tool for growth and development.
           </p>
       </div>
       <div class="options">
           <div class="option">
               <div class="option-icon">
                   <img src="https://cdn.sstatic.net/Img/home/public-qa.svg?v=d82acaa7df9f" alt="Public Q & A">
               </div>
               <div class="option-title">
                   Polls Section
               </div>
               <div class="option-description">
                This platform combines the engagement of social media with the informative nature of polls, creating an interactive space for sharing opinions and insights.
               </div>
               <div class="option-button">
                   <a href="{% url "stackbase:poll_list" %}" class="option-link btn btn-dark-blue">
                       Polls
                   </a>
               </div>
           </div>
           <div class="option">
               <div class="option-icon">
                   <img src="https://cdn.sstatic.net/Img/home/private-qa.svg?v=2c1de180b6d7" alt="Private Q & A">
               </div>
               <div class="option-title">
                   Latest Discussions
               </div>
               <div class="option-description">
                An online forum or chatroom where users can engage in discussions, exchange ideas, and collaborate, providing a digital space for meaningful interactions and knowledge sharing.
               </div>
               <div class="option-button">
                   <a href="{% url "stackbase:question-list" %}" class="option-link btn btn-orange">
                       Discussions
                   </a>
               </div>
           </div>
           <div class="option">
               <div class="option-icon">
                   <img src="https://cdn.sstatic.net/Img/home/jobs.svg?v=931d6c0863ee" alt="Browse jobs
">
               </div>
               <div class="option-title">
                   Goodies section
               </div>
               <div class="option-description">
                A system that incentivizes desired behaviors or actions by offering digital rewards such as points, badges, or virtual goods, encouraging engagement and participation.
               </div>
               <div class="option-button">
                   <a href="{% url "stackbase:goodies" %}" class="option-link btn btn-dark-blue">
                       Goodies
                   </a>
               </div>
           </div>
       </div>
   </div>
</section>






{% endblock content %}

Connect/stackprj/templates/polls.html
<strong>Polls abhi raste mein hain</strong>